@OPEN_WEATHER_API_KEY={{$dotenv OPEN_WEATHER_API_KEY}}
@WEATHER_API_KEY={{$dotenv WEATHER_API_KEY}}

@PORT={{$dotenv PORT}}
# valid
# @CEP=29304560
# invalid format
# @CEP=2930456a
# not exist
@CEP=00000000


###
# @name CallServer
GET http://localhost:{{PORT}}/{{CEP}}

###
# @name RequestCEP
GET https://viacep.com.br/ws/{{CEP}}/json

@localidade={{RequestCEP.response.body.localidade}}
@uf={{RequestCEP.response.body.uf}}

###
# @name RequestOpenWeather
GET https://api.openweathermap.org/data/2.5/weather?q={{localidade}},{{uf}},br&units=metric&appid={{OPEN_WEATHER_API_KEY}}

###
# @name RequestWeatherApi
GET http://api.weatherapi.com/v1/current.json?key={{WEATHER_API_KEY}}&q={{localidade}},{{uf}}
